### ISSUE TITLE
Model CPU

### ISSUE THREAD

**Issue by josephburnett** [pivotal/skenario#60]
We need to model requests consuming finite CPU resources on each pod.  We could model it explicitly (such as in pull request #38).  Or we could model it mathematically (such as [latency as a function of concurrent requests](https://github.com/pivotal/skenario/blob/7f37e52d3c7a37ddad7daa1c2bd8bdd0c402f96f/pkg/model/requests_processing.go#L113))

**Comment by josephburnett** [comment]
Our idea for modelling CPU utilization with approximation
- Continue to model latency with sakasegawaApproximation.
- Each request has a CPU utilization effect as a result of its CPU time and IO requirements
    - E.g. request { cpu=200ms, io=200ms } => 50% utilization (completes in 400ms when unencumbered using 200ms CPU == 50%)
    - fractionUtilised := saturateClamp(float64(currentUtilization) / float64(100))
    - delayTime := 1 + sakasegawaApproximation(fractionUtilised, float64(100), baseServiceTime)
- When we add the request to the stock we add its utilization to currentUtilization.
- And when the request is removed, we remove its utilization from currentUtilization.
- If the totalTime exceeds a timeout then we will instead schedule a movement after the timeout duration to failed requests.

**Comment by juliababkina** [comment]
Downsides of the model:

- It allows overloading of replicas. CPU is loaded more than 100%
- The model doesn't fully take into account that the more CPU is loaded the more time per request it needs. sakasegawaApproximation just calculates delay because of high cpu load but doesn’t take into account how much cpu is allocated for this particular request.

We refined the model.
Now it's Model with real CPU allocation.

Algorithm

1. Calculate free cpu capacity. 
2. Calculate how many cpu time we need to process this request.
3. Calculate how many time we need to process this request taking into account io time
4.  Calculate average cpu load for the request that is utilization for the request
5. Add this utilization to occupied cpu capacity
6. Calculate current utilization of cpu in percentage
7. Calculate delay by sakasegawaApproximation which plus processing time (which is calculated in the previous step) forms total time for processing a request 
8.

**Comment by juliababkina** [comment]
![Screenshot 2020-06-08 at 6 06 21 PM - Display 2](https://user-images.githubusercontent.com/65898660/84046589-fa7d2600-a9b2-11ea-825a-dd85d598e3d1.png)
